### ISSUE TITLE
gateway owner

### ISSUE THREAD

**Issue by TropicalSeedlings** [things4u/ESP-1ch-Gateway-v5.0#17]
Hi there..

My gateway is online, I can see it on the map but I have no idea how to add it to my console.. 
I can't see how to add Gateway Key from console to sketch.

On the map there is gateway ID only, any other info is unknown.

**Comment by craigpeacock** [comment]
You will need to be a little clearer with what your problem is and terminology, if you want help.

Do I assume you are unable to register the gateway on The Things Network (TTN) console (sketch)? 

If this is the case, under Register Gateway in the TTN Console, you need to click the tickbox "I'm using the legacy packet forwarder". This will then allow you to paste the Gateway ID into the Gateway EUI Field.

**Comment by TropicalSeedlings** [comment]
Thanks, problem solved.. almost..

In console I can see it as online but on the map there is still no owner neither any other info.. 
We'll se later if TTN servers need to refresh data

All data on the map has been updated.

**Comment by jlstanus** [comment]
@EI2KK Finally owner identity, model, placement has been updated?
