### ISSUE TITLE
Message is Received Every 2 minutes on TTN

### ISSUE THREAD

**Issue by Sukuri** [things4u/ESP-1ch-Gateway-v5.0#3]
Hi,

I was tested my node with Pi gateway before, the received message period on TTN is much faster. I set at node, the period is every 5 seconds.
But for this gateway, TTN receive the message for every 2 minutes.

Is it I'm running this Esp gateway normally,? but I still can get my data in order, no data lost, it's just delayed.

**Comment by platenspeler** [comment]
I cannot see what your problem is. But are you sure that the node will only send at channel 0, and did you set the CAD to 1 using the user interface. I do have about 7 of these single channel gateways working, and normally this means that the node does send its messages to all (9) channels and on all spreading factors
